# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8035483c06e717d4809391941dfc6a3796ae092a2bcdf91acb0749a6643136f7fcdd4005af4f9f461be1aaf9a5d7c0e6232c417a458095e81ca75f774fa5432c

test:
  secret_key_base: bd6377e9b0edf9e2c5545f6cc59641d169e8302240496f4d7f9be96844dda2c73ea68c0d750c0f0d4b4929dfc9a355a790997a825159a2d0a9ea60c06993f6c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
